/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Offers Data API
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.offers_data_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AccountrangestorpinsInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:33.222+05:30[Asia/Kolkata]")
public class AccountrangestorpinsInner {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("AccountRange")
  private AccountRange accountRange = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("RPIN")
  private RPIN RPIN = null;
  
  public AccountrangestorpinsInner accountRange(AccountRange accountRange) {
    this.accountRange = accountRange;
    return this;
  }

  
  /**
  * Get accountRange
  * @return accountRange
  **/
  @ApiModelProperty(value = "")
  public AccountRange getAccountRange() {
    return accountRange;
  }
  public void setAccountRange(AccountRange accountRange) {
    this.accountRange = accountRange;
  }
  
  public AccountrangestorpinsInner RPIN(RPIN RPIN) {
    this.RPIN = RPIN;
    return this;
  }

  
  /**
  * Get RPIN
  * @return RPIN
  **/
  @ApiModelProperty(value = "")
  public RPIN getRPIN() {
    return RPIN;
  }
  public void setRPIN(RPIN RPIN) {
    this.RPIN = RPIN;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountrangestorpinsInner accountrangestorpinsInner = (AccountrangestorpinsInner) o;
    return Objects.equals(this.accountRange, accountrangestorpinsInner.accountRange) &&
        Objects.equals(this.RPIN, accountrangestorpinsInner.RPIN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountRange, RPIN);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountrangestorpinsInner {\n");

    sb.append("    accountRange: ").append(toIndentedString(accountRange)).append("\n");
    sb.append("    RPIN: ").append(toIndentedString(RPIN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



