/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Offers Data API
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.offers_data_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;
import java.util.Objects;

/**
 * MerchantAddressInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:33.222+05:30[Asia/Kolkata]")
public class MerchantAddressInner {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("city")
  private String city = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("languages")
  private List<String> languages = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("indexNumber")
  private Integer indexNumber = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantKey")
  private Integer merchantKey = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("distance")
  private String distance = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("address1")
  private String address1 = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("address2")
  private String address2 = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("longtitude")
  private String longtitude = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("countryName")
  private String countryName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("latitude")
  private String latitude = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("state")
  private String state = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("key")
  private Integer key = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("languageName")
  private String languageName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("postalCode")
  private String postalCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantValue")
  private String merchantValue = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("languageIds")
  private List<Integer> languageIds = null;
  
  public MerchantAddressInner city(String city) {
    this.city = city;
    return this;
  }

  
  /**
  * the city of the merchant address 
  * @return city
  **/
  @ApiModelProperty(value = "the city of the merchant address ")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }
  
  public MerchantAddressInner languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  
  /**
  * returns all languages associated with the address
  * @return languages
  **/
  @ApiModelProperty(value = "returns all languages associated with the address")
  public List<String> getLanguages() {
    return languages;
  }
  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }
  
  public MerchantAddressInner indexNumber(Integer indexNumber) {
    this.indexNumber = indexNumber;
    return this;
  }

  
  /**
  * an integer identifier to signify the result index for the merchant address (specific to your request). Only displayed for a merchant address reference data request
  * @return indexNumber
  **/
  @ApiModelProperty(value = "an integer identifier to signify the result index for the merchant address (specific to your request). Only displayed for a merchant address reference data request")
  public Integer getIndexNumber() {
    return indexNumber;
  }
  public void setIndexNumber(Integer indexNumber) {
    this.indexNumber = indexNumber;
  }
  
  public MerchantAddressInner merchantKey(Integer merchantKey) {
    this.merchantKey = merchantKey;
    return this;
  }

  
  /**
  * the identifying value of the merchant. Only displayed for a merchant address reference data request
  * @return merchantKey
  **/
  @ApiModelProperty(value = "the identifying value of the merchant. Only displayed for a merchant address reference data request")
  public Integer getMerchantKey() {
    return merchantKey;
  }
  public void setMerchantKey(Integer merchantKey) {
    this.merchantKey = merchantKey;
  }
  
  public MerchantAddressInner distance(String distance) {
    this.distance = distance;
    return this;
  }

  
  /**
  * the distance from the origin to the merchant address. Only displayed when a geolocation filter has been applied and the address has valid latitude and longitude coordinates Max length: Computed - should be less than 20 bytes + distance unit
  * @return distance
  **/
  @ApiModelProperty(value = "the distance from the origin to the merchant address. Only displayed when a geolocation filter has been applied and the address has valid latitude and longitude coordinates Max length: Computed - should be less than 20 bytes + distance unit")
  public String getDistance() {
    return distance;
  }
  public void setDistance(String distance) {
    this.distance = distance;
  }
  
  public MerchantAddressInner address1(String address1) {
    this.address1 = address1;
    return this;
  }

  
  /**
  * the first line of the merchant address. Max length: 200 characters
  * @return address1
  **/
  @ApiModelProperty(value = "the first line of the merchant address. Max length: 200 characters")
  public String getAddress1() {
    return address1;
  }
  public void setAddress1(String address1) {
    this.address1 = address1;
  }
  
  public MerchantAddressInner address2(String address2) {
    this.address2 = address2;
    return this;
  }

  
  /**
  * the second line of the merchant. May return an empty String
  * @return address2
  **/
  @ApiModelProperty(value = "the second line of the merchant. May return an empty String")
  public String getAddress2() {
    return address2;
  }
  public void setAddress2(String address2) {
    this.address2 = address2;
  }
  
  public MerchantAddressInner longtitude(String longtitude) {
    this.longtitude = longtitude;
    return this;
  }

  
  /**
  * the longitude of the address
  * @return longtitude
  **/
  @ApiModelProperty(value = "the longitude of the address")
  public String getLongtitude() {
    return longtitude;
  }
  public void setLongtitude(String longtitude) {
    this.longtitude = longtitude;
  }
  
  public MerchantAddressInner countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

  
  /**
  * the country name 
  * @return countryName
  **/
  @ApiModelProperty(value = "the country name ")
  public String getCountryName() {
    return countryName;
  }
  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }
  
  public MerchantAddressInner latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

  
  /**
  * the latitude of the address
  * @return latitude
  **/
  @ApiModelProperty(value = "the latitude of the address")
  public String getLatitude() {
    return latitude;
  }
  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }
  
  public MerchantAddressInner state(String state) {
    this.state = state;
    return this;
  }

  
  /**
  * the state/province/territory of the merchant address 
  * @return state
  **/
  @ApiModelProperty(value = "the state/province/territory of the merchant address ")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }
  
  public MerchantAddressInner key(Integer key) {
    this.key = key;
    return this;
  }

  
  /**
  * the identifying value of the merchant address
  * @return key
  **/
  @ApiModelProperty(value = "the identifying value of the merchant address")
  public Integer getKey() {
    return key;
  }
  public void setKey(Integer key) {
    this.key = key;
  }
  
  public MerchantAddressInner languageName(String languageName) {
    this.languageName = languageName;
    return this;
  }

  
  /**
  * Deprecated; languages returns a complete list | A single language associated to the merchant address 
  * @return languageName
  **/
  @ApiModelProperty(value = "Deprecated; languages returns a complete list | A single language associated to the merchant address ")
  public String getLanguageName() {
    return languageName;
  }
  public void setLanguageName(String languageName) {
    this.languageName = languageName;
  }
  
  public MerchantAddressInner postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  
  /**
  * the postal code/zip code 
  * @return postalCode
  **/
  @ApiModelProperty(value = "the postal code/zip code ")
  public String getPostalCode() {
    return postalCode;
  }
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }
  
  public MerchantAddressInner merchantValue(String merchantValue) {
    this.merchantValue = merchantValue;
    return this;
  }

  
  /**
  * the default merchant name. Only displayed for a merchant address reference data request
  * @return merchantValue
  **/
  @ApiModelProperty(value = "the default merchant name. Only displayed for a merchant address reference data request")
  public String getMerchantValue() {
    return merchantValue;
  }
  public void setMerchantValue(String merchantValue) {
    this.merchantValue = merchantValue;
  }
  
  public MerchantAddressInner languageIds(List<Integer> languageIds) {
    this.languageIds = languageIds;
    return this;
  }

  
  /**
  * returns all keys for the languages associated with the address
  * @return languageIds
  **/
  @ApiModelProperty(value = "returns all keys for the languages associated with the address")
  public List<Integer> getLanguageIds() {
    return languageIds;
  }
  public void setLanguageIds(List<Integer> languageIds) {
    this.languageIds = languageIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantAddressInner merchantAddressInner = (MerchantAddressInner) o;
    return Objects.equals(this.city, merchantAddressInner.city) &&
        Objects.equals(this.languages, merchantAddressInner.languages) &&
        Objects.equals(this.indexNumber, merchantAddressInner.indexNumber) &&
        Objects.equals(this.merchantKey, merchantAddressInner.merchantKey) &&
        Objects.equals(this.distance, merchantAddressInner.distance) &&
        Objects.equals(this.address1, merchantAddressInner.address1) &&
        Objects.equals(this.address2, merchantAddressInner.address2) &&
        Objects.equals(this.longtitude, merchantAddressInner.longtitude) &&
        Objects.equals(this.countryName, merchantAddressInner.countryName) &&
        Objects.equals(this.latitude, merchantAddressInner.latitude) &&
        Objects.equals(this.state, merchantAddressInner.state) &&
        Objects.equals(this.key, merchantAddressInner.key) &&
        Objects.equals(this.languageName, merchantAddressInner.languageName) &&
        Objects.equals(this.postalCode, merchantAddressInner.postalCode) &&
        Objects.equals(this.merchantValue, merchantAddressInner.merchantValue) &&
        Objects.equals(this.languageIds, merchantAddressInner.languageIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, languages, indexNumber, merchantKey, distance, address1, address2, longtitude, countryName, latitude, state, key, languageName, postalCode, merchantValue, languageIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantAddressInner {\n");

    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    indexNumber: ").append(toIndentedString(indexNumber)).append("\n");
    sb.append("    merchantKey: ").append(toIndentedString(merchantKey)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    longtitude: ").append(toIndentedString(longtitude)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    languageName: ").append(toIndentedString(languageName)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    merchantValue: ").append(toIndentedString(merchantValue)).append("\n");
    sb.append("    languageIds: ").append(toIndentedString(languageIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



