/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Offers Data API
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.offers_data_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MerchantListInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:33.222+05:30[Asia/Kolkata]")
public class MerchantListInner {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchant")
  private String merchant = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantImages")
  private MerchantImages merchantImages = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantId")
  private Integer merchantId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantAddress")
  private MerchantAddress merchantAddress = null;
  
  public MerchantListInner merchant(String merchant) {
    this.merchant = merchant;
    return this;
  }

  
  /**
  * the merchant name. Max length: 200 characters
  * @return merchant
  **/
  @ApiModelProperty(value = "the merchant name. Max length: 200 characters")
  public String getMerchant() {
    return merchant;
  }
  public void setMerchant(String merchant) {
    this.merchant = merchant;
  }
  
  public MerchantListInner merchantImages(MerchantImages merchantImages) {
    this.merchantImages = merchantImages;
    return this;
  }

  
  /**
  * Get merchantImages
  * @return merchantImages
  **/
  @ApiModelProperty(value = "")
  public MerchantImages getMerchantImages() {
    return merchantImages;
  }
  public void setMerchantImages(MerchantImages merchantImages) {
    this.merchantImages = merchantImages;
  }
  
  public MerchantListInner merchantId(Integer merchantId) {
    this.merchantId = merchantId;
    return this;
  }

  
  /**
  * an identifier for the merchant
  * @return merchantId
  **/
  @ApiModelProperty(value = "an identifier for the merchant")
  public Integer getMerchantId() {
    return merchantId;
  }
  public void setMerchantId(Integer merchantId) {
    this.merchantId = merchantId;
  }
  
  public MerchantListInner merchantAddress(MerchantAddress merchantAddress) {
    this.merchantAddress = merchantAddress;
    return this;
  }

  
  /**
  * Get merchantAddress
  * @return merchantAddress
  **/
  @ApiModelProperty(value = "")
  public MerchantAddress getMerchantAddress() {
    return merchantAddress;
  }
  public void setMerchantAddress(MerchantAddress merchantAddress) {
    this.merchantAddress = merchantAddress;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantListInner merchantListInner = (MerchantListInner) o;
    return Objects.equals(this.merchant, merchantListInner.merchant) &&
        Objects.equals(this.merchantImages, merchantListInner.merchantImages) &&
        Objects.equals(this.merchantId, merchantListInner.merchantId) &&
        Objects.equals(this.merchantAddress, merchantListInner.merchantAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchant, merchantImages, merchantId, merchantAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantListInner {\n");

    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    merchantImages: ").append(toIndentedString(merchantImages)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    merchantAddress: ").append(toIndentedString(merchantAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



