/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Offers Data API
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.offers_data_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * OffersInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:33.222+05:30[Asia/Kolkata]")
public class OffersInner {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("isOfferEvent")
  private Boolean isOfferEvent = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantTerms")
  private MerchantTerms merchantTerms = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("programName")
  private String programName = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("barcode")
  private Barcode barcode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("promotingCountries")
  private PromotingCountries promotingCountries = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerMetadata")
  private OfferMetadata offerMetadata = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerSourceContact")
  private String offerSourceContact = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerId")
  private Integer offerId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionUrl")
  private String redemptionUrl = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("creativeGuidelines")
  private String creativeGuidelines = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerType")
  private OfferType offerType = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerSource")
  private String offerSource = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("featuredOfferIndicator")
  private Boolean featuredOfferIndicator = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("supData4")
  private SupData4 supData4 = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionCountries")
  private RedemptionCountries redemptionCountries = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("merchantList")
  private MerchantList merchantList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionEmail")
  private String redemptionEmail = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("supData2")
  private SupData2 supData2 = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("supData3")
  private SupData3 supData3 = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerContentId")
  private Integer offerContentId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("lastModifiedDateTime")
  private String lastModifiedDateTime = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("promotionRestictions")
  private PromotionRestictions promotionRestictions = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("languageId")
  private Integer languageId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionFormatInstructions")
  private String redemptionFormatInstructions = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerTitle")
  private String offerTitle = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("promotionToDate")
  private String promotionToDate = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("promotionFromDate")
  private String promotionFromDate = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("fAQs")
  private FAQs fAQs = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("supData1")
  private SupData1 supData1 = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("currentVersion")
  private Integer currentVersion = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("qrCode")
  private QrCode qrCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("creativeApprovalsEmail")
  private String creativeApprovalsEmail = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("imageList")
  private ImageList imageList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("businessSegmentList")
  private BusinessSegmentList businessSegmentList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("categorySubcategoryList")
  private CategorySubcategoryList categorySubcategoryList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("validityToDate")
  private String validityToDate = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerCopy")
  private OfferCopy offerCopy = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("visaTerms")
  private VisaTerms visaTerms = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerStatus")
  private String offerStatus = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("indexNumber")
  private Integer indexNumber = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("eventSubTitle")
  private String eventSubTitle = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("offerShortDescription")
  private OfferShortDescription offerShortDescription = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("dateLocations")
  private DateLocations dateLocations = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionCode")
  private String redemptionCode = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("programId")
  private Integer programId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("cardPaymentType")
  private CardPaymentType cardPaymentType = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("cardProductList")
  private CardProductList cardProductList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("accountrangestorpins")
  private Accountrangestorpins accountrangestorpins = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("validityFromDate")
  private String validityFromDate = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("rpins")
  private Rpins rpins = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionChannelList")
  private RedemptionChannelList redemptionChannelList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("activeIndicator")
  private Boolean activeIndicator = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("socialMediaSharingTypes")
  private SocialMediaSharingTypes socialMediaSharingTypes = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("promotionChannelList")
  private PromotionChannelList promotionChannelList = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("accountranges")
  private Accountranges accountranges = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("shareTitle")
  private String shareTitle = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("redemptionTelephone")
  private RedemptionTelephone redemptionTelephone = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("language")
  private String language = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("binstorpins")
  private Binstorpins binstorpins = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("legalCountryExclusions")
  private LegalCountryExclusions legalCountryExclusions = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("soldOut")
  private Boolean soldOut = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("bins")
  private Bins bins = null;
  
  public OffersInner isOfferEvent(Boolean isOfferEvent) {
    this.isOfferEvent = isOfferEvent;
    return this;
  }

  
  /**
  * the indicator to specify that the offer is an event
  * @return isOfferEvent
  **/
  @ApiModelProperty(value = "the indicator to specify that the offer is an event")
  public Boolean isIsOfferEvent() {
    return isOfferEvent;
  }
  public void setIsOfferEvent(Boolean isOfferEvent) {
    this.isOfferEvent = isOfferEvent;
  }
  
  public OffersInner merchantTerms(MerchantTerms merchantTerms) {
    this.merchantTerms = merchantTerms;
    return this;
  }

  
  /**
  * Get merchantTerms
  * @return merchantTerms
  **/
  @ApiModelProperty(value = "")
  public MerchantTerms getMerchantTerms() {
    return merchantTerms;
  }
  public void setMerchantTerms(MerchantTerms merchantTerms) {
    this.merchantTerms = merchantTerms;
  }
  
  public OffersInner programName(String programName) {
    this.programName = programName;
    return this;
  }

  
  /**
  * the name of the program. Max length: 500 characters. 
  * @return programName
  **/
  @ApiModelProperty(value = "the name of the program. Max length: 500 characters. ")
  public String getProgramName() {
    return programName;
  }
  public void setProgramName(String programName) {
    this.programName = programName;
  }
  
  public OffersInner barcode(Barcode barcode) {
    this.barcode = barcode;
    return this;
  }

  
  /**
  * Get barcode
  * @return barcode
  **/
  @ApiModelProperty(value = "")
  public Barcode getBarcode() {
    return barcode;
  }
  public void setBarcode(Barcode barcode) {
    this.barcode = barcode;
  }
  
  public OffersInner promotingCountries(PromotingCountries promotingCountries) {
    this.promotingCountries = promotingCountries;
    return this;
  }

  
  /**
  * Get promotingCountries
  * @return promotingCountries
  **/
  @ApiModelProperty(value = "")
  public PromotingCountries getPromotingCountries() {
    return promotingCountries;
  }
  public void setPromotingCountries(PromotingCountries promotingCountries) {
    this.promotingCountries = promotingCountries;
  }
  
  public OffersInner offerMetadata(OfferMetadata offerMetadata) {
    this.offerMetadata = offerMetadata;
    return this;
  }

  
  /**
  * Get offerMetadata
  * @return offerMetadata
  **/
  @ApiModelProperty(value = "")
  public OfferMetadata getOfferMetadata() {
    return offerMetadata;
  }
  public void setOfferMetadata(OfferMetadata offerMetadata) {
    this.offerMetadata = offerMetadata;
  }
  
  public OffersInner offerSourceContact(String offerSourceContact) {
    this.offerSourceContact = offerSourceContact;
    return this;
  }

  
  /**
  * the source agency contact asssociated with the offer. Max length: 100 characters
  * @return offerSourceContact
  **/
  @ApiModelProperty(value = "the source agency contact asssociated with the offer. Max length: 100 characters")
  public String getOfferSourceContact() {
    return offerSourceContact;
  }
  public void setOfferSourceContact(String offerSourceContact) {
    this.offerSourceContact = offerSourceContact;
  }
  
  public OffersInner offerId(Integer offerId) {
    this.offerId = offerId;
    return this;
  }

  
  /**
  * an identifier for the offer and any translations it may have
  * @return offerId
  **/
  @ApiModelProperty(value = "an identifier for the offer and any translations it may have")
  public Integer getOfferId() {
    return offerId;
  }
  public void setOfferId(Integer offerId) {
    this.offerId = offerId;
  }
  
  public OffersInner redemptionUrl(String redemptionUrl) {
    this.redemptionUrl = redemptionUrl;
    return this;
  }

  
  /**
  * the redemption URL of the offer. May return an empty String. Max length: 2048 characters
  * @return redemptionUrl
  **/
  @ApiModelProperty(value = "the redemption URL of the offer. May return an empty String. Max length: 2048 characters")
  public String getRedemptionUrl() {
    return redemptionUrl;
  }
  public void setRedemptionUrl(String redemptionUrl) {
    this.redemptionUrl = redemptionUrl;
  }
  
  public OffersInner creativeGuidelines(String creativeGuidelines) {
    this.creativeGuidelines = creativeGuidelines;
    return this;
  }

  
  /**
  * the creative guidelines of the offer. May return an empty String. Max length: 2GB
  * @return creativeGuidelines
  **/
  @ApiModelProperty(value = "the creative guidelines of the offer. May return an empty String. Max length: 2GB")
  public String getCreativeGuidelines() {
    return creativeGuidelines;
  }
  public void setCreativeGuidelines(String creativeGuidelines) {
    this.creativeGuidelines = creativeGuidelines;
  }
  
  public OffersInner offerType(OfferType offerType) {
    this.offerType = offerType;
    return this;
  }

  
  /**
  * Get offerType
  * @return offerType
  **/
  @ApiModelProperty(value = "")
  public OfferType getOfferType() {
    return offerType;
  }
  public void setOfferType(OfferType offerType) {
    this.offerType = offerType;
  }
  
  public OffersInner offerSource(String offerSource) {
    this.offerSource = offerSource;
    return this;
  }

  
  /**
  * the source agency asssociated with the offer. Max length: 200 characters
  * @return offerSource
  **/
  @ApiModelProperty(value = "the source agency asssociated with the offer. Max length: 200 characters")
  public String getOfferSource() {
    return offerSource;
  }
  public void setOfferSource(String offerSource) {
    this.offerSource = offerSource;
  }
  
  public OffersInner featuredOfferIndicator(Boolean featuredOfferIndicator) {
    this.featuredOfferIndicator = featuredOfferIndicator;
    return this;
  }

  
  /**
  * indicator whether the offer is featured
  * @return featuredOfferIndicator
  **/
  @ApiModelProperty(value = "indicator whether the offer is featured")
  public Boolean isFeaturedOfferIndicator() {
    return featuredOfferIndicator;
  }
  public void setFeaturedOfferIndicator(Boolean featuredOfferIndicator) {
    this.featuredOfferIndicator = featuredOfferIndicator;
  }
  
  public OffersInner supData4(SupData4 supData4) {
    this.supData4 = supData4;
    return this;
  }

  
  /**
  * Get supData4
  * @return supData4
  **/
  @ApiModelProperty(value = "")
  public SupData4 getSupData4() {
    return supData4;
  }
  public void setSupData4(SupData4 supData4) {
    this.supData4 = supData4;
  }
  
  public OffersInner redemptionCountries(RedemptionCountries redemptionCountries) {
    this.redemptionCountries = redemptionCountries;
    return this;
  }

  
  /**
  * Get redemptionCountries
  * @return redemptionCountries
  **/
  @ApiModelProperty(value = "")
  public RedemptionCountries getRedemptionCountries() {
    return redemptionCountries;
  }
  public void setRedemptionCountries(RedemptionCountries redemptionCountries) {
    this.redemptionCountries = redemptionCountries;
  }
  
  public OffersInner merchantList(MerchantList merchantList) {
    this.merchantList = merchantList;
    return this;
  }

  
  /**
  * Get merchantList
  * @return merchantList
  **/
  @ApiModelProperty(value = "")
  public MerchantList getMerchantList() {
    return merchantList;
  }
  public void setMerchantList(MerchantList merchantList) {
    this.merchantList = merchantList;
  }
  
  public OffersInner redemptionEmail(String redemptionEmail) {
    this.redemptionEmail = redemptionEmail;
    return this;
  }

  
  /**
  * the redemption Email of the offer. May return an empty String. Max length: 2048 characters
  * @return redemptionEmail
  **/
  @ApiModelProperty(value = "the redemption Email of the offer. May return an empty String. Max length: 2048 characters")
  public String getRedemptionEmail() {
    return redemptionEmail;
  }
  public void setRedemptionEmail(String redemptionEmail) {
    this.redemptionEmail = redemptionEmail;
  }
  
  public OffersInner supData2(SupData2 supData2) {
    this.supData2 = supData2;
    return this;
  }

  
  /**
  * Get supData2
  * @return supData2
  **/
  @ApiModelProperty(value = "")
  public SupData2 getSupData2() {
    return supData2;
  }
  public void setSupData2(SupData2 supData2) {
    this.supData2 = supData2;
  }
  
  public OffersInner supData3(SupData3 supData3) {
    this.supData3 = supData3;
    return this;
  }

  
  /**
  * Get supData3
  * @return supData3
  **/
  @ApiModelProperty(value = "")
  public SupData3 getSupData3() {
    return supData3;
  }
  public void setSupData3(SupData3 supData3) {
    this.supData3 = supData3;
  }
  
  public OffersInner offerContentId(Integer offerContentId) {
    this.offerContentId = offerContentId;
    return this;
  }

  
  /**
  * a unique identifier for the offer for the specific version and specified language
  * @return offerContentId
  **/
  @ApiModelProperty(value = "a unique identifier for the offer for the specific version and specified language")
  public Integer getOfferContentId() {
    return offerContentId;
  }
  public void setOfferContentId(Integer offerContentId) {
    this.offerContentId = offerContentId;
  }
  
  public OffersInner lastModifiedDateTime(String lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

  
  /**
  * the date and time the offer was last updated. Formatted as : DayOfWeek, DD Mon YYYY HH:MM:SS GMT
  * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "the date and time the offer was last updated. Formatted as : DayOfWeek, DD Mon YYYY HH:MM:SS GMT")
  public String getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }
  public void setLastModifiedDateTime(String lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }
  
  public OffersInner promotionRestictions(PromotionRestictions promotionRestictions) {
    this.promotionRestictions = promotionRestictions;
    return this;
  }

  
  /**
  * Get promotionRestictions
  * @return promotionRestictions
  **/
  @ApiModelProperty(value = "")
  public PromotionRestictions getPromotionRestictions() {
    return promotionRestictions;
  }
  public void setPromotionRestictions(PromotionRestictions promotionRestictions) {
    this.promotionRestictions = promotionRestictions;
  }
  
  public OffersInner languageId(Integer languageId) {
    this.languageId = languageId;
    return this;
  }

  
  /**
  * the identifier for the language of the offer
  * @return languageId
  **/
  @ApiModelProperty(value = "the identifier for the language of the offer")
  public Integer getLanguageId() {
    return languageId;
  }
  public void setLanguageId(Integer languageId) {
    this.languageId = languageId;
  }
  
  public OffersInner redemptionFormatInstructions(String redemptionFormatInstructions) {
    this.redemptionFormatInstructions = redemptionFormatInstructions;
    return this;
  }

  
  /**
  * the format instructions for redemption of offer. May return an empty String. Max length: 2048 characters
  * @return redemptionFormatInstructions
  **/
  @ApiModelProperty(value = "the format instructions for redemption of offer. May return an empty String. Max length: 2048 characters")
  public String getRedemptionFormatInstructions() {
    return redemptionFormatInstructions;
  }
  public void setRedemptionFormatInstructions(String redemptionFormatInstructions) {
    this.redemptionFormatInstructions = redemptionFormatInstructions;
  }
  
  public OffersInner offerTitle(String offerTitle) {
    this.offerTitle = offerTitle;
    return this;
  }

  
  /**
  * the title of the offer. Max length: 1000 characters
  * @return offerTitle
  **/
  @ApiModelProperty(value = "the title of the offer. Max length: 1000 characters")
  public String getOfferTitle() {
    return offerTitle;
  }
  public void setOfferTitle(String offerTitle) {
    this.offerTitle = offerTitle;
  }
  
  public OffersInner promotionToDate(String promotionToDate) {
    this.promotionToDate = promotionToDate;
    return this;
  }

  
  /**
  * the end of the promotion date range (in GMT). Formatted as: Mon DD, YYYY
  * @return promotionToDate
  **/
  @ApiModelProperty(value = "the end of the promotion date range (in GMT). Formatted as: Mon DD, YYYY")
  public String getPromotionToDate() {
    return promotionToDate;
  }
  public void setPromotionToDate(String promotionToDate) {
    this.promotionToDate = promotionToDate;
  }
  
  public OffersInner promotionFromDate(String promotionFromDate) {
    this.promotionFromDate = promotionFromDate;
    return this;
  }

  
  /**
  * the start of the promotion date range (in GMT). Formatted as: Mon DD, YYYY
  * @return promotionFromDate
  **/
  @ApiModelProperty(value = "the start of the promotion date range (in GMT). Formatted as: Mon DD, YYYY")
  public String getPromotionFromDate() {
    return promotionFromDate;
  }
  public void setPromotionFromDate(String promotionFromDate) {
    this.promotionFromDate = promotionFromDate;
  }
  
  public OffersInner fAQs(FAQs fAQs) {
    this.fAQs = fAQs;
    return this;
  }

  
  /**
  * Get fAQs
  * @return fAQs
  **/
  @ApiModelProperty(value = "")
  public FAQs getFAQs() {
    return fAQs;
  }
  public void setFAQs(FAQs fAQs) {
    this.fAQs = fAQs;
  }
  
  public OffersInner supData1(SupData1 supData1) {
    this.supData1 = supData1;
    return this;
  }

  
  /**
  * Get supData1
  * @return supData1
  **/
  @ApiModelProperty(value = "")
  public SupData1 getSupData1() {
    return supData1;
  }
  public void setSupData1(SupData1 supData1) {
    this.supData1 = supData1;
  }
  
  public OffersInner currentVersion(Integer currentVersion) {
    this.currentVersion = currentVersion;
    return this;
  }

  
  /**
  * the version of the offer
  * @return currentVersion
  **/
  @ApiModelProperty(value = "the version of the offer")
  public Integer getCurrentVersion() {
    return currentVersion;
  }
  public void setCurrentVersion(Integer currentVersion) {
    this.currentVersion = currentVersion;
  }
  
  public OffersInner qrCode(QrCode qrCode) {
    this.qrCode = qrCode;
    return this;
  }

  
  /**
  * Get qrCode
  * @return qrCode
  **/
  @ApiModelProperty(value = "")
  public QrCode getQrCode() {
    return qrCode;
  }
  public void setQrCode(QrCode qrCode) {
    this.qrCode = qrCode;
  }
  
  public OffersInner creativeApprovalsEmail(String creativeApprovalsEmail) {
    this.creativeApprovalsEmail = creativeApprovalsEmail;
    return this;
  }

  
  /**
  * the email of the creative approval of the offer. May return an empty String. Max length: 200 characters
  * @return creativeApprovalsEmail
  **/
  @ApiModelProperty(value = "the email of the creative approval of the offer. May return an empty String. Max length: 200 characters")
  public String getCreativeApprovalsEmail() {
    return creativeApprovalsEmail;
  }
  public void setCreativeApprovalsEmail(String creativeApprovalsEmail) {
    this.creativeApprovalsEmail = creativeApprovalsEmail;
  }
  
  public OffersInner imageList(ImageList imageList) {
    this.imageList = imageList;
    return this;
  }

  
  /**
  * Get imageList
  * @return imageList
  **/
  @ApiModelProperty(value = "")
  public ImageList getImageList() {
    return imageList;
  }
  public void setImageList(ImageList imageList) {
    this.imageList = imageList;
  }
  
  public OffersInner businessSegmentList(BusinessSegmentList businessSegmentList) {
    this.businessSegmentList = businessSegmentList;
    return this;
  }

  
  /**
  * Get businessSegmentList
  * @return businessSegmentList
  **/
  @ApiModelProperty(value = "")
  public BusinessSegmentList getBusinessSegmentList() {
    return businessSegmentList;
  }
  public void setBusinessSegmentList(BusinessSegmentList businessSegmentList) {
    this.businessSegmentList = businessSegmentList;
  }
  
  public OffersInner categorySubcategoryList(CategorySubcategoryList categorySubcategoryList) {
    this.categorySubcategoryList = categorySubcategoryList;
    return this;
  }

  
  /**
  * Get categorySubcategoryList
  * @return categorySubcategoryList
  **/
  @ApiModelProperty(value = "")
  public CategorySubcategoryList getCategorySubcategoryList() {
    return categorySubcategoryList;
  }
  public void setCategorySubcategoryList(CategorySubcategoryList categorySubcategoryList) {
    this.categorySubcategoryList = categorySubcategoryList;
  }
  
  public OffersInner validityToDate(String validityToDate) {
    this.validityToDate = validityToDate;
    return this;
  }

  
  /**
  * the end of the validity date range (in GMT). Formatted as: Mon DD, YYYY
  * @return validityToDate
  **/
  @ApiModelProperty(value = "the end of the validity date range (in GMT). Formatted as: Mon DD, YYYY")
  public String getValidityToDate() {
    return validityToDate;
  }
  public void setValidityToDate(String validityToDate) {
    this.validityToDate = validityToDate;
  }
  
  public OffersInner offerCopy(OfferCopy offerCopy) {
    this.offerCopy = offerCopy;
    return this;
  }

  
  /**
  * Get offerCopy
  * @return offerCopy
  **/
  @ApiModelProperty(value = "")
  public OfferCopy getOfferCopy() {
    return offerCopy;
  }
  public void setOfferCopy(OfferCopy offerCopy) {
    this.offerCopy = offerCopy;
  }
  
  public OffersInner visaTerms(VisaTerms visaTerms) {
    this.visaTerms = visaTerms;
    return this;
  }

  
  /**
  * Get visaTerms
  * @return visaTerms
  **/
  @ApiModelProperty(value = "")
  public VisaTerms getVisaTerms() {
    return visaTerms;
  }
  public void setVisaTerms(VisaTerms visaTerms) {
    this.visaTerms = visaTerms;
  }
  
  public OffersInner offerStatus(String offerStatus) {
    this.offerStatus = offerStatus;
    return this;
  }

  
  /**
  * the status of the offer
  * @return offerStatus
  **/
  @ApiModelProperty(value = "the status of the offer")
  public String getOfferStatus() {
    return offerStatus;
  }
  public void setOfferStatus(String offerStatus) {
    this.offerStatus = offerStatus;
  }
  
  public OffersInner indexNumber(Integer indexNumber) {
    this.indexNumber = indexNumber;
    return this;
  }

  
  /**
  * an integer identifier to signify the result index for the offer (specific to the request)
  * @return indexNumber
  **/
  @ApiModelProperty(value = "an integer identifier to signify the result index for the offer (specific to the request)")
  public Integer getIndexNumber() {
    return indexNumber;
  }
  public void setIndexNumber(Integer indexNumber) {
    this.indexNumber = indexNumber;
  }
  
  public OffersInner eventSubTitle(String eventSubTitle) {
    this.eventSubTitle = eventSubTitle;
    return this;
  }

  
  /**
  * the event sub title. Returns an empty String if the offer is not an event. Field is optional for events
  * @return eventSubTitle
  **/
  @ApiModelProperty(value = "the event sub title. Returns an empty String if the offer is not an event. Field is optional for events")
  public String getEventSubTitle() {
    return eventSubTitle;
  }
  public void setEventSubTitle(String eventSubTitle) {
    this.eventSubTitle = eventSubTitle;
  }
  
  public OffersInner offerShortDescription(OfferShortDescription offerShortDescription) {
    this.offerShortDescription = offerShortDescription;
    return this;
  }

  
  /**
  * Get offerShortDescription
  * @return offerShortDescription
  **/
  @ApiModelProperty(value = "")
  public OfferShortDescription getOfferShortDescription() {
    return offerShortDescription;
  }
  public void setOfferShortDescription(OfferShortDescription offerShortDescription) {
    this.offerShortDescription = offerShortDescription;
  }
  
  public OffersInner dateLocations(DateLocations dateLocations) {
    this.dateLocations = dateLocations;
    return this;
  }

  
  /**
  * Get dateLocations
  * @return dateLocations
  **/
  @ApiModelProperty(value = "")
  public DateLocations getDateLocations() {
    return dateLocations;
  }
  public void setDateLocations(DateLocations dateLocations) {
    this.dateLocations = dateLocations;
  }
  
  public OffersInner redemptionCode(String redemptionCode) {
    this.redemptionCode = redemptionCode;
    return this;
  }

  
  /**
  * the redemption code of the offer. May return an empty String. Max length: 1024 characters
  * @return redemptionCode
  **/
  @ApiModelProperty(value = "the redemption code of the offer. May return an empty String. Max length: 1024 characters")
  public String getRedemptionCode() {
    return redemptionCode;
  }
  public void setRedemptionCode(String redemptionCode) {
    this.redemptionCode = redemptionCode;
  }
  
  public OffersInner programId(Integer programId) {
    this.programId = programId;
    return this;
  }

  
  /**
  * the identifier for the program
  * @return programId
  **/
  @ApiModelProperty(value = "the identifier for the program")
  public Integer getProgramId() {
    return programId;
  }
  public void setProgramId(Integer programId) {
    this.programId = programId;
  }
  
  public OffersInner cardPaymentType(CardPaymentType cardPaymentType) {
    this.cardPaymentType = cardPaymentType;
    return this;
  }

  
  /**
  * Get cardPaymentType
  * @return cardPaymentType
  **/
  @ApiModelProperty(value = "")
  public CardPaymentType getCardPaymentType() {
    return cardPaymentType;
  }
  public void setCardPaymentType(CardPaymentType cardPaymentType) {
    this.cardPaymentType = cardPaymentType;
  }
  
  public OffersInner cardProductList(CardProductList cardProductList) {
    this.cardProductList = cardProductList;
    return this;
  }

  
  /**
  * Get cardProductList
  * @return cardProductList
  **/
  @ApiModelProperty(value = "")
  public CardProductList getCardProductList() {
    return cardProductList;
  }
  public void setCardProductList(CardProductList cardProductList) {
    this.cardProductList = cardProductList;
  }
  
  public OffersInner accountrangestorpins(Accountrangestorpins accountrangestorpins) {
    this.accountrangestorpins = accountrangestorpins;
    return this;
  }

  
  /**
  * Get accountrangestorpins
  * @return accountrangestorpins
  **/
  @ApiModelProperty(value = "")
  public Accountrangestorpins getAccountrangestorpins() {
    return accountrangestorpins;
  }
  public void setAccountrangestorpins(Accountrangestorpins accountrangestorpins) {
    this.accountrangestorpins = accountrangestorpins;
  }
  
  public OffersInner validityFromDate(String validityFromDate) {
    this.validityFromDate = validityFromDate;
    return this;
  }

  
  /**
  * the start of the validity date range (in GMT). Formatted as: Mon DD, YYYY
  * @return validityFromDate
  **/
  @ApiModelProperty(value = "the start of the validity date range (in GMT). Formatted as: Mon DD, YYYY")
  public String getValidityFromDate() {
    return validityFromDate;
  }
  public void setValidityFromDate(String validityFromDate) {
    this.validityFromDate = validityFromDate;
  }
  
  public OffersInner rpins(Rpins rpins) {
    this.rpins = rpins;
    return this;
  }

  
  /**
  * Get rpins
  * @return rpins
  **/
  @ApiModelProperty(value = "")
  public Rpins getRpins() {
    return rpins;
  }
  public void setRpins(Rpins rpins) {
    this.rpins = rpins;
  }
  
  public OffersInner redemptionChannelList(RedemptionChannelList redemptionChannelList) {
    this.redemptionChannelList = redemptionChannelList;
    return this;
  }

  
  /**
  * Get redemptionChannelList
  * @return redemptionChannelList
  **/
  @ApiModelProperty(value = "")
  public RedemptionChannelList getRedemptionChannelList() {
    return redemptionChannelList;
  }
  public void setRedemptionChannelList(RedemptionChannelList redemptionChannelList) {
    this.redemptionChannelList = redemptionChannelList;
  }
  
  public OffersInner activeIndicator(Boolean activeIndicator) {
    this.activeIndicator = activeIndicator;
    return this;
  }

  
  /**
  * indicator whether offer is active
  * @return activeIndicator
  **/
  @ApiModelProperty(value = "indicator whether offer is active")
  public Boolean isActiveIndicator() {
    return activeIndicator;
  }
  public void setActiveIndicator(Boolean activeIndicator) {
    this.activeIndicator = activeIndicator;
  }
  
  public OffersInner socialMediaSharingTypes(SocialMediaSharingTypes socialMediaSharingTypes) {
    this.socialMediaSharingTypes = socialMediaSharingTypes;
    return this;
  }

  
  /**
  * Get socialMediaSharingTypes
  * @return socialMediaSharingTypes
  **/
  @ApiModelProperty(value = "")
  public SocialMediaSharingTypes getSocialMediaSharingTypes() {
    return socialMediaSharingTypes;
  }
  public void setSocialMediaSharingTypes(SocialMediaSharingTypes socialMediaSharingTypes) {
    this.socialMediaSharingTypes = socialMediaSharingTypes;
  }
  
  public OffersInner promotionChannelList(PromotionChannelList promotionChannelList) {
    this.promotionChannelList = promotionChannelList;
    return this;
  }

  
  /**
  * Get promotionChannelList
  * @return promotionChannelList
  **/
  @ApiModelProperty(value = "")
  public PromotionChannelList getPromotionChannelList() {
    return promotionChannelList;
  }
  public void setPromotionChannelList(PromotionChannelList promotionChannelList) {
    this.promotionChannelList = promotionChannelList;
  }
  
  public OffersInner accountranges(Accountranges accountranges) {
    this.accountranges = accountranges;
    return this;
  }

  
  /**
  * Get accountranges
  * @return accountranges
  **/
  @ApiModelProperty(value = "")
  public Accountranges getAccountranges() {
    return accountranges;
  }
  public void setAccountranges(Accountranges accountranges) {
    this.accountranges = accountranges;
  }
  
  public OffersInner shareTitle(String shareTitle) {
    this.shareTitle = shareTitle;
    return this;
  }

  
  /**
  * the social media sharing title. Returns an empty String if the offer does not have social media sharing types.
  * @return shareTitle
  **/
  @ApiModelProperty(value = "the social media sharing title. Returns an empty String if the offer does not have social media sharing types.")
  public String getShareTitle() {
    return shareTitle;
  }
  public void setShareTitle(String shareTitle) {
    this.shareTitle = shareTitle;
  }
  
  public OffersInner redemptionTelephone(RedemptionTelephone redemptionTelephone) {
    this.redemptionTelephone = redemptionTelephone;
    return this;
  }

  
  /**
  * Get redemptionTelephone
  * @return redemptionTelephone
  **/
  @ApiModelProperty(value = "")
  public RedemptionTelephone getRedemptionTelephone() {
    return redemptionTelephone;
  }
  public void setRedemptionTelephone(RedemptionTelephone redemptionTelephone) {
    this.redemptionTelephone = redemptionTelephone;
  }
  
  public OffersInner language(String language) {
    this.language = language;
    return this;
  }

  
  /**
  * the name of the language. Max length: 100 characters
  * @return language
  **/
  @ApiModelProperty(value = "the name of the language. Max length: 100 characters")
  public String getLanguage() {
    return language;
  }
  public void setLanguage(String language) {
    this.language = language;
  }
  
  public OffersInner binstorpins(Binstorpins binstorpins) {
    this.binstorpins = binstorpins;
    return this;
  }

  
  /**
  * Get binstorpins
  * @return binstorpins
  **/
  @ApiModelProperty(value = "")
  public Binstorpins getBinstorpins() {
    return binstorpins;
  }
  public void setBinstorpins(Binstorpins binstorpins) {
    this.binstorpins = binstorpins;
  }
  
  public OffersInner legalCountryExclusions(LegalCountryExclusions legalCountryExclusions) {
    this.legalCountryExclusions = legalCountryExclusions;
    return this;
  }

  
  /**
  * Get legalCountryExclusions
  * @return legalCountryExclusions
  **/
  @ApiModelProperty(value = "")
  public LegalCountryExclusions getLegalCountryExclusions() {
    return legalCountryExclusions;
  }
  public void setLegalCountryExclusions(LegalCountryExclusions legalCountryExclusions) {
    this.legalCountryExclusions = legalCountryExclusions;
  }
  
  public OffersInner soldOut(Boolean soldOut) {
    this.soldOut = soldOut;
    return this;
  }

  
  /**
  * indicator whether offer is sold out
  * @return soldOut
  **/
  @ApiModelProperty(value = "indicator whether offer is sold out")
  public Boolean isSoldOut() {
    return soldOut;
  }
  public void setSoldOut(Boolean soldOut) {
    this.soldOut = soldOut;
  }
  
  public OffersInner bins(Bins bins) {
    this.bins = bins;
    return this;
  }

  
  /**
  * Get bins
  * @return bins
  **/
  @ApiModelProperty(value = "")
  public Bins getBins() {
    return bins;
  }
  public void setBins(Bins bins) {
    this.bins = bins;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OffersInner offersInner = (OffersInner) o;
    return Objects.equals(this.isOfferEvent, offersInner.isOfferEvent) &&
        Objects.equals(this.merchantTerms, offersInner.merchantTerms) &&
        Objects.equals(this.programName, offersInner.programName) &&
        Objects.equals(this.barcode, offersInner.barcode) &&
        Objects.equals(this.promotingCountries, offersInner.promotingCountries) &&
        Objects.equals(this.offerMetadata, offersInner.offerMetadata) &&
        Objects.equals(this.offerSourceContact, offersInner.offerSourceContact) &&
        Objects.equals(this.offerId, offersInner.offerId) &&
        Objects.equals(this.redemptionUrl, offersInner.redemptionUrl) &&
        Objects.equals(this.creativeGuidelines, offersInner.creativeGuidelines) &&
        Objects.equals(this.offerType, offersInner.offerType) &&
        Objects.equals(this.offerSource, offersInner.offerSource) &&
        Objects.equals(this.featuredOfferIndicator, offersInner.featuredOfferIndicator) &&
        Objects.equals(this.supData4, offersInner.supData4) &&
        Objects.equals(this.redemptionCountries, offersInner.redemptionCountries) &&
        Objects.equals(this.merchantList, offersInner.merchantList) &&
        Objects.equals(this.redemptionEmail, offersInner.redemptionEmail) &&
        Objects.equals(this.supData2, offersInner.supData2) &&
        Objects.equals(this.supData3, offersInner.supData3) &&
        Objects.equals(this.offerContentId, offersInner.offerContentId) &&
        Objects.equals(this.lastModifiedDateTime, offersInner.lastModifiedDateTime) &&
        Objects.equals(this.promotionRestictions, offersInner.promotionRestictions) &&
        Objects.equals(this.languageId, offersInner.languageId) &&
        Objects.equals(this.redemptionFormatInstructions, offersInner.redemptionFormatInstructions) &&
        Objects.equals(this.offerTitle, offersInner.offerTitle) &&
        Objects.equals(this.promotionToDate, offersInner.promotionToDate) &&
        Objects.equals(this.promotionFromDate, offersInner.promotionFromDate) &&
        Objects.equals(this.fAQs, offersInner.fAQs) &&
        Objects.equals(this.supData1, offersInner.supData1) &&
        Objects.equals(this.currentVersion, offersInner.currentVersion) &&
        Objects.equals(this.qrCode, offersInner.qrCode) &&
        Objects.equals(this.creativeApprovalsEmail, offersInner.creativeApprovalsEmail) &&
        Objects.equals(this.imageList, offersInner.imageList) &&
        Objects.equals(this.businessSegmentList, offersInner.businessSegmentList) &&
        Objects.equals(this.categorySubcategoryList, offersInner.categorySubcategoryList) &&
        Objects.equals(this.validityToDate, offersInner.validityToDate) &&
        Objects.equals(this.offerCopy, offersInner.offerCopy) &&
        Objects.equals(this.visaTerms, offersInner.visaTerms) &&
        Objects.equals(this.offerStatus, offersInner.offerStatus) &&
        Objects.equals(this.indexNumber, offersInner.indexNumber) &&
        Objects.equals(this.eventSubTitle, offersInner.eventSubTitle) &&
        Objects.equals(this.offerShortDescription, offersInner.offerShortDescription) &&
        Objects.equals(this.dateLocations, offersInner.dateLocations) &&
        Objects.equals(this.redemptionCode, offersInner.redemptionCode) &&
        Objects.equals(this.programId, offersInner.programId) &&
        Objects.equals(this.cardPaymentType, offersInner.cardPaymentType) &&
        Objects.equals(this.cardProductList, offersInner.cardProductList) &&
        Objects.equals(this.accountrangestorpins, offersInner.accountrangestorpins) &&
        Objects.equals(this.validityFromDate, offersInner.validityFromDate) &&
        Objects.equals(this.rpins, offersInner.rpins) &&
        Objects.equals(this.redemptionChannelList, offersInner.redemptionChannelList) &&
        Objects.equals(this.activeIndicator, offersInner.activeIndicator) &&
        Objects.equals(this.socialMediaSharingTypes, offersInner.socialMediaSharingTypes) &&
        Objects.equals(this.promotionChannelList, offersInner.promotionChannelList) &&
        Objects.equals(this.accountranges, offersInner.accountranges) &&
        Objects.equals(this.shareTitle, offersInner.shareTitle) &&
        Objects.equals(this.redemptionTelephone, offersInner.redemptionTelephone) &&
        Objects.equals(this.language, offersInner.language) &&
        Objects.equals(this.binstorpins, offersInner.binstorpins) &&
        Objects.equals(this.legalCountryExclusions, offersInner.legalCountryExclusions) &&
        Objects.equals(this.soldOut, offersInner.soldOut) &&
        Objects.equals(this.bins, offersInner.bins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isOfferEvent, merchantTerms, programName, barcode, promotingCountries, offerMetadata, offerSourceContact, offerId, redemptionUrl, creativeGuidelines, offerType, offerSource, featuredOfferIndicator, supData4, redemptionCountries, merchantList, redemptionEmail, supData2, supData3, offerContentId, lastModifiedDateTime, promotionRestictions, languageId, redemptionFormatInstructions, offerTitle, promotionToDate, promotionFromDate, fAQs, supData1, currentVersion, qrCode, creativeApprovalsEmail, imageList, businessSegmentList, categorySubcategoryList, validityToDate, offerCopy, visaTerms, offerStatus, indexNumber, eventSubTitle, offerShortDescription, dateLocations, redemptionCode, programId, cardPaymentType, cardProductList, accountrangestorpins, validityFromDate, rpins, redemptionChannelList, activeIndicator, socialMediaSharingTypes, promotionChannelList, accountranges, shareTitle, redemptionTelephone, language, binstorpins, legalCountryExclusions, soldOut, bins);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OffersInner {\n");

    sb.append("    isOfferEvent: ").append(toIndentedString(isOfferEvent)).append("\n");
    sb.append("    merchantTerms: ").append(toIndentedString(merchantTerms)).append("\n");
    sb.append("    programName: ").append(toIndentedString(programName)).append("\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    promotingCountries: ").append(toIndentedString(promotingCountries)).append("\n");
    sb.append("    offerMetadata: ").append(toIndentedString(offerMetadata)).append("\n");
    sb.append("    offerSourceContact: ").append(toIndentedString(offerSourceContact)).append("\n");
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    redemptionUrl: ").append(toIndentedString(redemptionUrl)).append("\n");
    sb.append("    creativeGuidelines: ").append(toIndentedString(creativeGuidelines)).append("\n");
    sb.append("    offerType: ").append(toIndentedString(offerType)).append("\n");
    sb.append("    offerSource: ").append(toIndentedString(offerSource)).append("\n");
    sb.append("    featuredOfferIndicator: ").append(toIndentedString(featuredOfferIndicator)).append("\n");
    sb.append("    supData4: ").append(toIndentedString(supData4)).append("\n");
    sb.append("    redemptionCountries: ").append(toIndentedString(redemptionCountries)).append("\n");
    sb.append("    merchantList: ").append(toIndentedString(merchantList)).append("\n");
    sb.append("    redemptionEmail: ").append(toIndentedString(redemptionEmail)).append("\n");
    sb.append("    supData2: ").append(toIndentedString(supData2)).append("\n");
    sb.append("    supData3: ").append(toIndentedString(supData3)).append("\n");
    sb.append("    offerContentId: ").append(toIndentedString(offerContentId)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    promotionRestictions: ").append(toIndentedString(promotionRestictions)).append("\n");
    sb.append("    languageId: ").append(toIndentedString(languageId)).append("\n");
    sb.append("    redemptionFormatInstructions: ").append(toIndentedString(redemptionFormatInstructions)).append("\n");
    sb.append("    offerTitle: ").append(toIndentedString(offerTitle)).append("\n");
    sb.append("    promotionToDate: ").append(toIndentedString(promotionToDate)).append("\n");
    sb.append("    promotionFromDate: ").append(toIndentedString(promotionFromDate)).append("\n");
    sb.append("    fAQs: ").append(toIndentedString(fAQs)).append("\n");
    sb.append("    supData1: ").append(toIndentedString(supData1)).append("\n");
    sb.append("    currentVersion: ").append(toIndentedString(currentVersion)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    creativeApprovalsEmail: ").append(toIndentedString(creativeApprovalsEmail)).append("\n");
    sb.append("    imageList: ").append(toIndentedString(imageList)).append("\n");
    sb.append("    businessSegmentList: ").append(toIndentedString(businessSegmentList)).append("\n");
    sb.append("    categorySubcategoryList: ").append(toIndentedString(categorySubcategoryList)).append("\n");
    sb.append("    validityToDate: ").append(toIndentedString(validityToDate)).append("\n");
    sb.append("    offerCopy: ").append(toIndentedString(offerCopy)).append("\n");
    sb.append("    visaTerms: ").append(toIndentedString(visaTerms)).append("\n");
    sb.append("    offerStatus: ").append(toIndentedString(offerStatus)).append("\n");
    sb.append("    indexNumber: ").append(toIndentedString(indexNumber)).append("\n");
    sb.append("    eventSubTitle: ").append(toIndentedString(eventSubTitle)).append("\n");
    sb.append("    offerShortDescription: ").append(toIndentedString(offerShortDescription)).append("\n");
    sb.append("    dateLocations: ").append(toIndentedString(dateLocations)).append("\n");
    sb.append("    redemptionCode: ").append(toIndentedString(redemptionCode)).append("\n");
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("    cardPaymentType: ").append(toIndentedString(cardPaymentType)).append("\n");
    sb.append("    cardProductList: ").append(toIndentedString(cardProductList)).append("\n");
    sb.append("    accountrangestorpins: ").append(toIndentedString(accountrangestorpins)).append("\n");
    sb.append("    validityFromDate: ").append(toIndentedString(validityFromDate)).append("\n");
    sb.append("    rpins: ").append(toIndentedString(rpins)).append("\n");
    sb.append("    redemptionChannelList: ").append(toIndentedString(redemptionChannelList)).append("\n");
    sb.append("    activeIndicator: ").append(toIndentedString(activeIndicator)).append("\n");
    sb.append("    socialMediaSharingTypes: ").append(toIndentedString(socialMediaSharingTypes)).append("\n");
    sb.append("    promotionChannelList: ").append(toIndentedString(promotionChannelList)).append("\n");
    sb.append("    accountranges: ").append(toIndentedString(accountranges)).append("\n");
    sb.append("    shareTitle: ").append(toIndentedString(shareTitle)).append("\n");
    sb.append("    redemptionTelephone: ").append(toIndentedString(redemptionTelephone)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    binstorpins: ").append(toIndentedString(binstorpins)).append("\n");
    sb.append("    legalCountryExclusions: ").append(toIndentedString(legalCountryExclusions)).append("\n");
    sb.append("    soldOut: ").append(toIndentedString(soldOut)).append("\n");
    sb.append("    bins: ").append(toIndentedString(bins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



