/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Offers Data API
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.offers_data_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * OfferMetadataInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:33.222+05:30[Asia/Kolkata]")
public class OfferMetadataInner {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("metaKey")
  private String metaKey = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("metaId")
  private Integer metaId = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("metaValue")
  private String metaValue = null;
  
  public OfferMetadataInner metaKey(String metaKey) {
    this.metaKey = metaKey;
    return this;
  }

  
  /**
  * a user-provided key 
  * @return metaKey
  **/
  @ApiModelProperty(value = "a user-provided key ")
  public String getMetaKey() {
    return metaKey;
  }
  public void setMetaKey(String metaKey) {
    this.metaKey = metaKey;
  }
  
  public OfferMetadataInner metaId(Integer metaId) {
    this.metaId = metaId;
    return this;
  }

  
  /**
  * an identifier
  * @return metaId
  **/
  @ApiModelProperty(value = "an identifier")
  public Integer getMetaId() {
    return metaId;
  }
  public void setMetaId(Integer metaId) {
    this.metaId = metaId;
  }
  
  public OfferMetadataInner metaValue(String metaValue) {
    this.metaValue = metaValue;
    return this;
  }

  
  /**
  * a user-provided value 
  * @return metaValue
  **/
  @ApiModelProperty(value = "a user-provided value ")
  public String getMetaValue() {
    return metaValue;
  }
  public void setMetaValue(String metaValue) {
    this.metaValue = metaValue;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferMetadataInner offerMetadataInner = (OfferMetadataInner) o;
    return Objects.equals(this.metaKey, offerMetadataInner.metaKey) &&
        Objects.equals(this.metaId, offerMetadataInner.metaId) &&
        Objects.equals(this.metaValue, offerMetadataInner.metaValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metaKey, metaId, metaValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferMetadataInner {\n");

    sb.append("    metaKey: ").append(toIndentedString(metaKey)).append("\n");
    sb.append("    metaId: ").append(toIndentedString(metaId)).append("\n");
    sb.append("    metaValue: ").append(toIndentedString(metaValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



