/* ----------------------------------------------------------------------------------------------------------------------
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
---------------------------------------------------------------------------------------------------------------------- */

/*
 * Offers Data API
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.offers_data_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * RetrieveOffersByFiltergetResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-12-19T10:49:33.222+05:30[Asia/Kolkata]")
public class RetrieveOffersByFiltergetResponse {

  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("ReturnedResults")
  private Integer returnedResults = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("Offers")
  private Offers offers = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("TotalFoundResults")
  private Integer totalFoundResults = null;
  
  
  @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
  @JsonProperty("StartIndex")
  private Integer startIndex = null;
  
  public RetrieveOffersByFiltergetResponse returnedResults(Integer returnedResults) {
    this.returnedResults = returnedResults;
    return this;
  }

  
  /**
  * The number of offers returned in the offer reponse. A maximum of 500 offers are returned
  * @return returnedResults
  **/
  @ApiModelProperty(value = "The number of offers returned in the offer reponse. A maximum of 500 offers are returned")
  public Integer getReturnedResults() {
    return returnedResults;
  }
  public void setReturnedResults(Integer returnedResults) {
    this.returnedResults = returnedResults;
  }
  
  public RetrieveOffersByFiltergetResponse offers(Offers offers) {
    this.offers = offers;
    return this;
  }

  
  /**
  * Get offers
  * @return offers
  **/
  @ApiModelProperty(value = "")
  public Offers getOffers() {
    return offers;
  }
  public void setOffers(Offers offers) {
    this.offers = offers;
  }
  
  public RetrieveOffersByFiltergetResponse totalFoundResults(Integer totalFoundResults) {
    this.totalFoundResults = totalFoundResults;
    return this;
  }

  
  /**
  * The total number of offers that match the request
  * @return totalFoundResults
  **/
  @ApiModelProperty(value = "The total number of offers that match the request")
  public Integer getTotalFoundResults() {
    return totalFoundResults;
  }
  public void setTotalFoundResults(Integer totalFoundResults) {
    this.totalFoundResults = totalFoundResults;
  }
  
  public RetrieveOffersByFiltergetResponse startIndex(Integer startIndex) {
    this.startIndex = startIndex;
    return this;
  }

  
  /**
  * The index at which the offer response begins. The value corresponds with the start_index parameter. If it was not provided, defaults to 1
  * @return startIndex
  **/
  @ApiModelProperty(value = "The index at which the offer response begins. The value corresponds with the start_index parameter. If it was not provided, defaults to 1")
  public Integer getStartIndex() {
    return startIndex;
  }
  public void setStartIndex(Integer startIndex) {
    this.startIndex = startIndex;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveOffersByFiltergetResponse retrieveOffersByFiltergetResponse = (RetrieveOffersByFiltergetResponse) o;
    return Objects.equals(this.returnedResults, retrieveOffersByFiltergetResponse.returnedResults) &&
        Objects.equals(this.offers, retrieveOffersByFiltergetResponse.offers) &&
        Objects.equals(this.totalFoundResults, retrieveOffersByFiltergetResponse.totalFoundResults) &&
        Objects.equals(this.startIndex, retrieveOffersByFiltergetResponse.startIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnedResults, offers, totalFoundResults, startIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveOffersByFiltergetResponse {\n");

    sb.append("    returnedResults: ").append(toIndentedString(returnedResults)).append("\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("    totalFoundResults: ").append(toIndentedString(totalFoundResults)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



